server:
  port: 8004
spring:
  application:
    name: ocean-article #指定服务名
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/ocean_article?characterEncoding=UTF8&useSSL=false
    username: root
    password: 123456
  jpa:
    database: MySQL
    show-sql: true
  redis:
    host: 127.0.0.1
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:6868/eureka/
  instance:
    prefer-ip-address: true